name: src
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  expandable_text: ^2.3.0
  appinio_video_player: ^1.2.2
  syncfusion_flutter_pdfviewer: ^23.1.42
  persistent_bottom_nav_bar: any
  rating_dialog: ^2.0.4
  multiselect: ^0.1.0
  multi_dropdown: ^2.1.0
  get: ^4.6.6
  provider:
  toastification:
  syncfusion_flutter_calendar: ^23.1.44
  chewie: ^1.7.0
  video_player:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
